[tool.poetry]
name = "presigned-url"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.34.106"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
